version: "3"
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/html:/var/www/
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80
    extra_hosts:
     - host.docker.internal:host-gateway
  php:
    build: ./docker/php
    volumes:
      - ./docker/nginx/html:/var/www/
      - ./docker/php/phpsocket:/var/run/
    ports:
      - "9000:9000"